#Docker Compose file
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trackchat-network
      
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${PORT_APP:-3000}:3000"
    environment:
      - SOCKET_SERVER_INTERNAL_URL=${SOCKET_SERVER_INTERNAL_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
    depends_on:
      db:
        condition: service_healthy
      socket:
        condition: service_started
    networks:
      - trackchat-network

  socket:
    build: ./socket
    env_file:
      - .env
    environment:
      - APP_URL=${APP_URL}
    ports:
      - "${PORT_SOCKET:-4000}:4000"
    restart: always
    networks:
      - trackchat-network
  

networks:
  trackchat-network:
    driver: bridge

volumes:
  pgdata: