services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trackchat-network
      
  app:
    build:
      context: .
      args:
        # Importante: O build precisa saber a URL pÃºblica (1701)
        - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
    env_file:
      - .env
    ports:
      # Mapeia Host 1700 -> Container 3000
      - "${PORT_APP}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - SOCKET_SERVER_INTERNAL_URL=${SOCKET_SERVER_INTERNAL_URL}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
      - APP_URL=${APP_URL}
    depends_on:
      db:
        condition: service_healthy
      socket:
        condition: service_started
    networks:
      - trackchat-network

  socket:
    build: ./socket
    env_file:
      - .env
    environment:
      - APP_URL=${APP_URL}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      # Mapeia Host 1701 -> Container 4000
      - "${PORT_SOCKET}:4000"
    restart: always
    networks:
      - trackchat-network

networks:
  trackchat-network:
    driver: bridge

volumes:
  pgdata: