services:
  app:
    build:
      context: .
      args:
        # Resolve a interpolação ${DOMAIN} antes de enviar ao Dockerfile
        - NEXT_PUBLIC_SOCKET_URL=http://${DOMAIN}:4000
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - socket
    networks:
      - trackchat-network

  socket:
    build: ./socket
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN} # Força a passagem da variável
    ports:
      - "4000:4000"
    restart: always
