services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SOCKET_URL=http://${DOMAIN}:1701
    env_file:
      - .env
    ports:
      - "1700:3000"
    depends_on:
      db:
        condition: service_healthy
      socket:
        condition: service_started
    networks:
      - trackchat-network

  socket:
    build: ./socket
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - PORT=4000
    ports:
      - "1701:4000"
    restart: always
    networks:
      - trackchat-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U AiAtende -d trackchat"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1750:5432"
    networks:
      - trackchat-network

networks:
  trackchat-network:
    driver: bridge

volumes:
  pgdata: